version: '3.8'
services:
  langchain-app:
    build: 
      context: .
      dockerfile: .\DockerFile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development