version: '3.8'
services:
  frontend:
    build: 
      context: langchain-app
      dockerfile: .\DockerFile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build: 
      context: backend
      dockerfile: .\DockerFile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    